-- Use database and schema
USE DATABASE ECOMMERCE_DB;
USE SCHEMA ANALYTICS;

-- Create S3 storage integration
CREATE STORAGE INTEGRATION ECOMMERCE_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN =
    'arn:aws:iam::482178643648:role/SnowflakeS3GoldAccessRole'
  STORAGE_ALLOWED_LOCATIONS = (
    's3://ecommerce-customer-intelligence/gold/'
  );

-- Create external stage
CREATE STAGE ECOMMERCE_GOLD_STAGE
  URL = 's3://ecommerce-customer-intelligence/gold/'
  STORAGE_INTEGRATION = ECOMMERCE_S3_INTEGRATION;

-- Customer Intelligence external table
CREATE OR REPLACE EXTERNAL TABLE CUSTOMER_INTELLIGENCE_EXT
WITH LOCATION = @ECOMMERCE_GOLD_STAGE/customer_intelligence/
FILE_FORMAT = (TYPE = PARQUET)
TABLE_FORMAT = DELTA
REFRESH_ON_CREATE = FALSE
AUTO_REFRESH = FALSE;

ALTER EXTERNAL TABLE CUSTOMER_INTELLIGENCE_EXT REFRESH;

-- Product Performance external table
CREATE OR REPLACE EXTERNAL TABLE PRODUCT_PERFORMANCE_EXT
WITH LOCATION = @ECOMMERCE_GOLD_STAGE/product_performance/
FILE_FORMAT = (TYPE = PARQUET)
TABLE_FORMAT = DELTA
REFRESH_ON_CREATE = FALSE
AUTO_REFRESH = FALSE;

ALTER EXTERNAL TABLE PRODUCT_PERFORMANCE_EXT REFRESH;

-- Fraud Analytics external table
CREATE OR REPLACE EXTERNAL TABLE FRAUD_ANALYTICS_EXT
WITH LOCATION = @ECOMMERCE_GOLD_STAGE/fraud_analytics/
FILE_FORMAT = (TYPE = PARQUET)
TABLE_FORMAT = DELTA
REFRESH_ON_CREATE = FALSE
AUTO_REFRESH = FALSE;

ALTER EXTERNAL TABLE FRAUD_ANALYTICS_EXT REFRESH;